### ISSUE TITLE
django-rest-framework 3.7 not supported currently

### ISSUE THREAD

**Issue by madisvain** [namespace-ee/drf-sideloading#14]
https://github.com/namespace-ee/django-rest-framework-sideloading/blob/master/setup.py#L61

**Comment by madisvain** [comment]
Accidentally commited this to main branch:
https://github.com/namespace-ee/django-rest-framework-sideloading/commit/19a2e703bede15f75e0006c895381356e2ce7796

We can review this and discuss if we can assume that if there is not a major release change for drf then the project should support it.

**Comment by demonno** [comment]
I have added  `djangorestframework==3.7.1` in tox

https://github.com/namespace-ee/django-rest-framework-sideloading/blob/e5a025e7051133416633fc89da3e11aa4b5e3ebc/tox.ini#L5-L7

And all existing tests are passing.

If there are more specific bugs please report - https://github.com/namespace-ee/django-rest-framework-sideloading/blob/master/CONTRIBUTING.rst#report-bugs
