### ISSUE TITLE
Filtering of sideloaded entities does not seem to work

### ISSUE THREAD

**Issue by demonno** [namespace-ee/drf-sideloading#40]
If you define a serialiser like this 

https://github.com/namespace-ee/django-rest-framework-sideloading/blob/8da55552c2d081d1ba57aa7a61646abc4f251edd/tests/test_products_api.py#L446-L456

And then ask to sideload followings entities `category`, `categories` or `category,categories`.
In all three cases you get the same results:

```
{
"categories":
"category":
"products":
}
```

Created a test case to capture this behaviour: https://github.com/namespace-ee/django-rest-framework-sideloading/pull/39

**Comment by tonisvain** [comment]
did not filter between fields with the same source, as the serializer is initialized with SOURCE values.
fixed with passing fields that are required to the serializer.
